[package]
name = "annealingcollager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
panic = "abort"
codegen-units = 1
lto = "fat"

[dependencies]
fastrand = "2.0.1"
image = "0.24.8"
